### PR TITLE
next Polish translations, next strings translated.

### PR DESCRIPTION
**Pull request by paxcoder**
Hi again.
My translation is getting ready, just only few files and strings are not translated.
Have a good day.

### CODE REVIEW

**Comment by kode54** [comment]
Still missing the Preferences panes.

`Preferences/Preferences/Base.lproj`

Located under `Cog > Resources > Preference Panes > Preferences > Resources` in the two nibs there. I suggest forking from the `sparkle` branch for this change, since there's an updater string in there that somehow originally got removed in the `main` branch.

**Comment by paxcoder** [comment]
it would be better if you could somehow get those strings to the main branch.

Wiadomość napisana przez Christopher Snowhill ***@***.***> w dniu 11.07.2022, o godz. 01:41:

﻿

Still missing the Preferences panes.

Preferences/Preferences/Base.lproj

Located under Cog > Resources > Preference Panes > Preferences > Resources in the two nibs there. I suggest forking from the sparkle branch for this change, since there's an updater string in there that somehow originally got removed in the main branch.

**Comment by kode54** [comment]
They will never exist in the `main` branch, because that is the App Store branch. If you would rather base your translation on the `sparkle` branch, that would be fine. The strings won't be removed from the other branch when they are imported into it.

**Comment by paxcoder** [comment]
I will not translate those for now.
I would like to see the new version in the App Store, before I continue my work.

Wiadomość napisana przez Christopher Snowhill ***@***.******@***.***>> w dniu 11.07.2022, o godz. 08:50:



They will never exist in the main branch, because that is the App Store branch. If you would rather base your translation on the sparkle branch, that would be fine. The strings won't be removed from the other branch when they are imported into it.

**Pull request merged**
