### PR TITLE
Two gigaseconds

### PR DESCRIPTION
**Pull request by JanX2**
This branch/PR contains improvements to time handling in the Cog UI. Please review. :)

I hope my humor doesn’t clash here. :D

### CODE REVIEW

**Comment by nevack** [comment]
@kode54 Build is failing for no reason, can you look at it?

**Comment by nevack** [comment]
@JanX2 Please, provide some screenshots.
Also squash all of your commits if the work is done here.

**Comment by kode54** [comment]
> @kode54 Build is failing for no reason, can you look at it?

Build is failing because it's trying to import the secret keychain, which only works for collaborators.

**Comment by JanX2** [comment]
@nevack Thank you for reminding me to provide screenshots.

**Pull request merged**
